FROM node:20-alpine

# প্রয়োজনীয় টুলস ইনস্টল
RUN apk add --no-cache git

WORKDIR /app

# ডিপেন্ডেন্সি ইনস্টল
COPY package*.json ./
RUN npm install

# সব কোড কপি
COPY . .

EXPOSE 5000

# রান করার কমান্ড
CMD ["npm", "run", "dev"]
